insert into users (firstname, lastname, password, mail, role, class) values ('Kenna', 'Lengthorn', '44nfWwhim5k', 'klengthorn0@google.it', 1, 'INNOPRAN');
insert into users (firstname, lastname, password, mail, role, class) values ('Margret', 'Drought', 'j0nYqiCNaMh', 'mdrought1@hostgator.com', 1, 'good neighbor pharmacy night time');
insert into users (firstname, lastname, password, mail, role, class) values ('Julius', 'Flooks', 'GCWa6EzUaXLv', 'jflooks2@arstechnica.com', 2, 'Gentamicin Sulfate in Sodium Chloride');
insert into users (firstname, lastname, password, mail, role, class) values ('Elspeth', 'Goodbairn', 'rUKCaZoGKNqB', 'egoodbairn3@irs.gov', 2, 'Ciprofloxacin');
insert into users (firstname, lastname, password, mail, role, class) values ('Allix', 'Chansonne', 'itMjTB', 'achansonne4@over-blog.com', 1, 'Nail MD');
insert into users (firstname, lastname, password, mail, role, class) values ('Maureen', 'Faughny', 'fOCIviEl', 'mfaughny5@baidu.com', 1, 'TRAMADOL HYDROCHLORIDE');
insert into users (firstname, lastname, password, mail, role, class) values ('Mariann', 'Bonefant', 'DBLu5eq', 'mbonefant6@yellowpages.com', 2, 'Lisinopril');
insert into users (firstname, lastname, password, mail, role, class) values ('Derwin', 'Oakly', '8X6Kqrmaq2', 'doakly7@cbc.ca', 1, 'Malin and Goetz');
insert into users (firstname, lastname, password, mail, role, class) values ('Tito', 'Hendriksen', 'YcwwvMt4', 'thendriksen8@senate.gov', 1, 'Reef Safe SPF 45');
insert into users (firstname, lastname, password, mail, role, class) values ('Alphard', 'Castiglio', 'MUyYYf', 'acastiglio9@google.cn', 2, 'BD E-Z Care');
insert into users (firstname, lastname, password, mail, role, class) values ('Kenneth', 'Tower', 'WDl528tqI', 'ktowera@patch.com', 1, 'Isometheptene Mucate, Caffeine, and Acetaminophen');
insert into users (firstname, lastname, password, mail, role, class) values ('Teresita', 'Sawney', 'OGRg7qb1', 'tsawneyb@e-recht24.de', 2, 'Benazepril Hydrochloride');
insert into users (firstname, lastname, password, mail, role, class) values ('Ingamar', 'Walworth', '4bBtPNsSPFAw', 'iwalworthc@sourceforge.net', 2, 'Tussin Chest');
insert into users (firstname, lastname, password, mail, role, class) values ('Bill', 'Swansbury', 'vzliyilS92vo', 'bswansburyd@apple.com', 1, 'smart sense tussin dm');
insert into users (firstname, lastname, password, mail, role, class) values ('Huntlee', 'Castrillo', 'jf16H7ZNi0ct', 'hcastrilloe@delicious.com', 2, 'Furosemide');
insert into users (firstname, lastname, password, mail, role, class) values ('Blair', 'Finley', 'VPlKWmhtf', 'bfinleyf@exblog.jp', 1, 'COLLAGEN HD FOUNDATION');
insert into users (firstname, lastname, password, mail, role, class) values ('Elke', 'Dionisio', 'TBVmcs70JFF', 'edionisiog@berkeley.edu', 2, 'Losartan Potassium');
insert into users (firstname, lastname, password, mail, role, class) values ('Chris', 'Cuxson', 'hMstkYV46h', 'ccuxsonh@sun.com', 1, 'Day Time');
insert into users (firstname, lastname, password, mail, role, class) values ('Rosalynd', 'Greve', 'fl3XyD9', 'rgrevei@nasa.gov', 2, 'Red Snapper');
insert into users (firstname, lastname, password, mail, role, class) values ('Ludwig', 'Picton', 'nde0YV8e', 'lpictonj@rakuten.co.jp', 2, 'HurriCaine');
insert into users (firstname, lastname, password, mail, role, class) values ('Vera', 'Walsham', 'XfMCUXc', 'vwalshamk@plala.or.jp', 1, 'Diamond White Oil-Free Brilliant Sun Protection');
insert into users (firstname, lastname, password, mail, role, class) values ('Annamarie', 'McWaters', 'KOPdt6TsO', 'amcwatersl@cornell.edu', 1, 'Gabapentin');
insert into users (firstname, lastname, password, mail, role, class) values ('Perl', 'Blampy', 'EFLhtT6SCDB', 'pblampym@google.co.uk', 1, 'Glumetza');
insert into users (firstname, lastname, password, mail, role, class) values ('Marten', 'Farquar', '7MIEblKVp', 'mfarquarn@tiny.cc', 1, 'Citalopram Hydrobromide');
insert into users (firstname, lastname, password, mail, role, class) values ('Kele', 'Hawkswood', '4d9JZXLmU3R', 'khawkswoodo@sciencedaily.com', 1, 'DIMENHYDRINATE');
insert into users (firstname, lastname, password, mail, role, class) values ('Jacintha', 'Lodford', 'NlMRiOy', 'jlodfordp@utexas.edu', 1, 'MISSHA ALL AROUND SAFE BLOCK ESSENCE SUN');
insert into users (firstname, lastname, password, mail, role, class) values ('Obed', 'McCard', 'wadzMxGlLiU', 'omccardq@meetup.com', 2, 'West Cottonwood');
insert into users (firstname, lastname, password, mail, role, class) values ('Fanchette', 'Anglish', 'Jx6McCK0fTWl', 'fanglishr@github.io', 1, 'Atorvastatin Calcium');
insert into users (firstname, lastname, password, mail, role, class) values ('Sukey', 'Velde', 'fWNdwY5em', 'sveldes@indiegogo.com', 1, 'Naproxen');
insert into users (firstname, lastname, password, mail, role, class) values ('Carson', 'Northcliffe', 'skitj4O', 'cnorthcliffet@comsenz.com', 2, 'Allegra--D 24 Hour');
insert into users (firstname, lastname, password, mail, role, class) values ('Todd', 'Bignall', 'Tu2jwB', 'tbignallu@webmd.com', 2, 'Oxygen');
insert into users (firstname, lastname, password, mail, role, class) values ('Cristina', 'Ewan', '66g4Kd3j', 'cewanv@surveymonkey.com', 2, 'Childrens Acetaminophen');
insert into users (firstname, lastname, password, mail, role, class) values ('Dennet', 'Noell', 'bRr8lbAnJtld', 'dnoellw@jugem.jp', 2, 'Etoposide');
insert into users (firstname, lastname, password, mail, role, class) values ('Tuck', 'Manilo', 'afKM8LW', 'tmanilox@elpais.com', 1, 'Indomethacin');
insert into users (firstname, lastname, password, mail, role, class) values ('Koral', 'Eckford', 'cA5jUWKk', 'keckfordy@desdev.cn', 1, 'Clonidine Hydrochloride');
insert into users (firstname, lastname, password, mail, role, class) values ('Valentin', 'Newbatt', 'fjLF3C', 'vnewbattz@google.co.jp', 2, 'AMYL NITROSUM');
insert into users (firstname, lastname, password, mail, role, class) values ('Galina', 'Abbess', 'DZdoD9w9s', 'gabbess10@state.gov', 1, 'Silver Maple');
insert into users (firstname, lastname, password, mail, role, class) values ('Nobe', 'Allmond', 'GBj9Uw1HJOW9', 'nallmond11@un.org', 2, 'Summer Berry Antibacterial Foaming Hand Wash');
insert into users (firstname, lastname, password, mail, role, class) values ('Haydon', 'Challicum', 'HZmrXYkGFoCB', 'hchallicum12@reverbnation.com', 2, 'Methocarbamol');
insert into users (firstname, lastname, password, mail, role, class) values ('Atalanta', 'Orrocks', 'bVKTztjV', 'aorrocks13@woothemes.com', 2, 'Lotrel');
insert into users (firstname, lastname, password, mail, role, class) values ('Aubry', 'Billiard', '7nT2Kz', 'abilliard14@cnbc.com', 2, 'omeprazole/sodium bicarbonate');
insert into users (firstname, lastname, password, mail, role, class) values ('Shaylynn', 'Furley', '38vFp7d', 'sfurley15@meetup.com', 2, 'Gelsemium Sempervirens 30c');
insert into users (firstname, lastname, password, mail, role, class) values ('Grissel', 'Botger', 'yCfpI41', 'gbotger16@ocn.ne.jp', 1, 'Vivacaine');
insert into users (firstname, lastname, password, mail, role, class) values ('Isac', 'Oxtoby', '9ur3C9duJVr', 'ioxtoby17@google.ru', 2, 'OMESEC');
insert into users (firstname, lastname, password, mail, role, class) values ('Colly', 'Seage', 'CStRieXvV', 'cseage18@flavors.me', 1, 'Triamterene and Hydrochlorothiazide');
insert into users (firstname, lastname, password, mail, role, class) values ('Perri', 'Gwin', 'phbAKP0sh', 'pgwin19@skyrock.com', 2, 'Quiet Calm');
insert into users (firstname, lastname, password, mail, role, class) values ('Roxanna', 'Idale', 'sGcZtKWSW', 'ridale1a@sogou.com', 2, 'ONDANSETRON');
insert into users (firstname, lastname, password, mail, role, class) values ('Florella', 'Orrock', 'xbMCz0nW', 'forrock1b@ca.gov', 2, 'Lunesta');
insert into users (firstname, lastname, password, mail, role, class) values ('Gilly', 'Medhurst', 'yzc3Hht53A9f', 'gmedhurst1c@patch.com', 1, 'CTx3 Rinse');
insert into users (firstname, lastname, password, mail, role, class) values ('Sampson', 'Hartles', 'j47l3EZussoO', 'shartles1d@shareasale.com', 2, 'CHAPSTICK CLASSICS SPEARMINT');
